name: build

on: [push, pull_request]

jobs:
  clippy:
    # Runs Clippy to check for lints in the Rust code
    name: Clippy Lint Check
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.91.0
          components: clippy

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  doc:
    # Builds project documentation, including private items
    name: Docs Check
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check docs
        run: cargo doc --no-deps --document-private-items

  cli-build:
    # Builds the CLI binary located in the `cli` folder using release profile
    name: Build CLI
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup default stable

      - name: Build CLI release
        run: |
          cd cli
          cargo build --release